services:
  dd-agent:
    agent:
      ports:
        - 8125/udp
        - 8126/tcp
    image: datadog/agent:latest
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
      - DD_APM_ANALYZED_SPANS="mighty-v2-backend|django.request=1"
    privileged: true
    scale:
      cpu: 128
      memory: 128
    volumes:
      - /cgroup/:/host/sys/fs/cgroup/
      - /proc/:/host/proc/
      - /var/run/docker.sock:/var/run/docker.sock
