services:
  dd-agent:
    build: .
    agent:
      ports:
        - 8125/udp
        - 8126/tcp
    environment:
      - DATABASE_HOST
      - DATABASE_PASSWORD
      - DD_API_KEY
      - DD_APM_ANALYZED_SPANS
      - DD_APM_ENABLED
    privileged: true
    scale:
      cpu: 128
      memory: 128
    volumes:
      - /cgroup/:/host/sys/fs/cgroup/
      - /proc/:/host/proc/
      - /var/run/docker.sock:/var/run/docker.sock
