services:
  dd-agent:
    build: .
    agent:
      ports:
        - 8125/udp
        - 8126/tcp
    environment:
      - DATABASE_HOST
      - DATABASE_PASSWORD
      - DD_API_KEY
      - DD_APM_ANALYZED_SPANS
      - DD_APM_ENABLED
      - DD_ENV
      - DD_PROCESS_AGENT_ENABLED
      - DD_REMOTE_CONFIGURATION_ENABLED
      - DD_SYSTEM_PROBE_ENABLED
      - RABBITMQ_API_URL
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
    privileged: true
    scale:
      cpu: 128
      memory: 128
    volumes:
      - /proc/:/host/proc/
      - /sys/fs/cgroup/:/host/sys/fs/cgroup/
      - /sys/kernel/debug:/sys/kernel/debug
      - /var/run/docker.sock:/var/run/docker.sock
